spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abook
    username: root
    password: 326616
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8181

mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml